
replicas: 4

configmap:
  data:
    CUSTOM_HEADER: 'This is on the PROD environment!'

image:
  name: devopsjourney1/mywebapp
  tag: latest

image2:
  name: devopsjourney1/mywebapp
  tag: latest

envVariables:
    - name: DRUPAL_DATABASE_PASSWORD
      value: "bitnami"
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"
    - name: DRUPAL_DATABASE_NAME
      value: "bitnami_drupal"
    - name: DRUPAL_DATABASE_HOST
      value: "mariadb"
      