apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-todo
  labels:
    app: {{ .Values.appName }}-todo
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-todo
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-todo
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "{{ .Values.image2.name }}:{{ .Values.image2.tag }}"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
          requests:
            memory: "50Mi" 
            cpu: "100m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "100Mi"
            cpu: "150m"