apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-wordpress
  labels:
    app: {{ .Values.appName }}-wordpress
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-wordpress
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "{{ .Values.image2.name }}:{{ .Values.image2.tag }}"
        ports:
        - containerPort: 80
        envFrom:
        env:
          {{- toYaml .Values.webapp.envVariables | nindent 12 }}
        resources:
          requests:
            memory: "500Mi" 
            cpu: "400m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "1008Mi"
            cpu: "800m"