apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-wordpress
  labels:
    app: {{ .Values.appName }}-wordpress
spec:
  ports:
  - port: 81
    targetPort: 81
    protocol: TCP
    name: flask
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: NodePort
